// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikyxwxlfwkvjwhbixjhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreXh3eGxmd2t2andoYml4amhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDk0MzEsImV4cCI6MjA3MzI4NTQzMX0.TuXNH4Kpdw68pbL3KfupooJPAiVKPUTLMRFA8-oRL8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});